// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "dehwyy",
            "url": "https://t.me/dehwyy",
            "email": "dehwyyy@gmail.icom"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/whip": {
            "post": {
                "consumes": [
                    "application/sdp"
                ],
                "produces": [
                    "application/sdp"
                ],
                "parameters": [
                    {
                        "description": "*SDPOffer* generated by **OBS**",
                        "name": "SDPOffer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "*Authorization* token set by **OBS**",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ServerSDPAnswer",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "IETF WHIP",
        "url": "https://datatracker.ietf.org/doc/html/draft-ietf-wish-whip-16"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "WhipWhep API",
	Description:      "**Whip** and **Whep** protocol implementation. `OBS => Server` - *Whip*. `Server <=> Client` (e.g from browser) - *Whep*. It's a **bridge** to make `WebRTC` connection.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
